name: Github Page Deploy Workflow
on:
  push:
    branches: [huakUpdate]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm install --save-dev @babel/plugin-proposal-private-property-in-object --legacy-peer-deps
      - run: npm run build --legacy-peer-deps
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
